FirstProject/Controllers/BossViewModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Windows.Forms.VisualStyles;
using FirstProject.Data;
using FirstProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace FirstProject.Controllers
{
    public class BossViewModelsController : Controller
    {
        private BossContext db = new BossContext();

        // GET: BossViewModels
        [Authorize]
        public ActionResult Index()
        {
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            ApplicationUser user = null;
            user = userManager.FindByName(User.Identity.Name);
            if (User.Identity.IsAuthenticated)
            {
                if (user == null)
                {
                    return RedirectToAction("LogOffProg", "Account");
                }
            }
            return View(db.BossViewModels.ToList());
        }

        // GET: BossViewModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BossViewModel bossViewModel = db.BossViewModels.Find(id);
            if (bossViewModel == null)
            {
                return HttpNotFound();
            }
            return View(bossViewModel);
        }

        // GET: BossViewModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BossViewModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,KdCount,KdTime,Color")] BossViewModel bossViewModel)
        {
            if (ModelState.IsValid)
            {
                var dtnow_now = DateTime.Now.ToUniversalTime();
                TimeZoneInfo moscowTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time");
                DateTime dtnow = TimeZoneInfo.ConvertTimeFromUtc(dtnow_now, moscowTimeZone);
                var time_str = string.Format("{0}.{1}.{2}", dtnow.Hour < 10 ? "0" + dtnow.Hour.ToString() : dtnow.Hour.ToString()
                    , dtnow.Minute < 10 ? "0" + dtnow.Minute.ToString() : dtnow.Minute.ToString()
                    , dtnow.Second < 10 ? "0" + dtnow.Second.ToString() : dtnow.Second.ToString());
                var res = string.Format("{0}.{1}.{2} {3}:{4}:{5}", dtnow.Day, dtnow.Month, dtnow.Year, dtnow.Hour, dtnow.Minute, dtnow.Second);
                bossViewModel.LastTime = res;
                bossViewModel.KdTime = bossViewModel.KdTime.Replace(':', '.').Replace(',', '.').Replace(' ', '.');
                db.BossViewModels.Add(bossViewModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            return View(bossViewModel);
        }

        // GET: BossViewModels/Edit/5
        public ActionResult Edit(int? id, bool fl = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BossViewModel bossViewModel = db.BossViewModels.Find(id);
            if (bossViewModel == null)
            {
                return HttpNotFound();
            }

            if (!fl)
            {
                return View(bossViewModel);
            }

            return Edit(bossViewModel,fl);
        }

        // POST: BossViewModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,KdCount,KdTime,LastTime,Color")] BossViewModel bossViewModel,bool fl = false)
        {
            if (ModelState.IsValid)
            {
                var dtnow_now = DateTime.Now.ToUniversalTime(); 
                TimeZoneInfo moscowTimeZone = TimeZoneInfo.FindSystemTimeZoneById("Russian Standard Time");
                DateTime dtnow = TimeZoneInfo.ConvertTimeFromUtc(dtnow_now, moscowTimeZone);
                HistoryModel hist = new HistoryModel();
                hist.Name = User.Identity.Name;
                
                
                if (fl)
                {
                    var res = string.Format("{0}.{1}.{2} {3}:{4}:{5}", dtnow.Day, dtnow.Month, dtnow.Year, dtnow.Hour, dtnow.Minute, dtnow.Second);
                    bossViewModel.LastTime = res;
                    hist.Type = "Ткнул упал сейчас";
                }
                else
                {
                    var mass = bossViewModel.LastTime.Split(' ');
                    var str = string.Empty;
                    for (int i = 1; i < mass.Length; i++)
                    {
                        str += mass[i] + ' ';
                    }

                    str = str.Remove(str.Length - 1);
                    bossViewModel.LastTime = mass[0] + ' ' + str.Replace('.', ':').Replace(',', ':').Replace('-', ':')
                        .Replace(' ', ':');
                    hist.Type = "Ткнул точное время";
                }

                hist.LastTime = bossViewModel.LastTime;
                hist.BossName = bossViewModel.Name;
                db.Entry(bossViewModel).State = EntityState.Modified;
                db.History.Add(hist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bossViewModel);
        }

        // GET: BossViewModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BossViewModel bossViewModel = db.BossViewModels.Find(id);
            if (bossViewModel == null)
            {
                return HttpNotFound();
            }
            return View(bossViewModel);
        }

        // POST: BossViewModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BossViewModel bossViewModel = db.BossViewModels.Find(id);
            db.BossViewModels.Remove(bossViewModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FirstProject/Views/BossViewModels/Create.cshtml
@model FirstProject.Models.BossViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/SetColorScripts.js")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>BossViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.KdTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KdTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KdTime, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <p><input type="color" value="цвет" name="имя" id="palitra" >
                <input type="button" value="Выбрать" onclick="set_color_name('palitra','color_text')">
                </p>
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control", @id = "color_text" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

FirstProject/Views/BossViewModels/Delete.cshtml
@model FirstProject.Models.BossViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <div class="container">
    <h3>Вы точно хотите удалить босса?</h3>
    <div>
        
        <hr />
        <dl class="dl-horizontal" hidden="true">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.KdCount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.KdCount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.KdTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.KdTime)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Да" class="button_1596547873487" /> |
                @Html.ActionLink("Вернуться назад", "Index")
            </div>
        }
    </div>
    </div>
</body>
</html>

FirstProject/Views/BossViewModels/Details.cshtml
@model FirstProject.Models.BossViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>BossViewModel</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.KdCount)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.KdCount)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.KdTime)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.KdTime)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

FirstProject/Views/BossViewModels/Edit.cshtml
@model FirstProject.Models.BossViewModel

@using (@Html.BeginForm("Edit","BossViewModels",FormMethod.Post))
{
    <div class="modal-content">
        <div class="modal-header">
            <button class="close" data-dismiss="modal" area-hidden="true">X</button>
            
        </div>
        <div class="modal-body">
            <dl class="dl-horizontal">
                @Html.AntiForgeryToken()

                
                    <h4>Редактирование времени смерти</h4>
                    <hr/>
                    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
                    @Html.HiddenFor(model => model.Id)

                    
                            @Html.HiddenFor(model => model.Name)
                            @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                     

                    
                            @Html.HiddenFor(model => model.KdTime)
                            @Html.ValidationMessageFor(model => model.KdTime, "", new {@class = "text-danger"})
                     
                @Html.HiddenFor(model => model.Color)
                @Html.ValidationMessageFor(model => model.Color, "", new {@class = "text-danger"})

                    
                @Html.HiddenFor(model => model.KdCount)
                            @Html.ValidationMessageFor(model => model.KdCount, "", new {@class = "text-danger"})
                    
                    
                        @Html.LabelFor(model => model.LastTime)
                      
                            @Html.EditorFor(model => model.LastTime)
                            @Html.ValidationMessageFor(model => model.LastTime, "", new {@class = "text-danger"})
                    

               
                        <input type="submit" value="Save" class="btn btn-default"/>
                  
                    
                


                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>

           </dl>
        </div>
    </div>
}

FirstProject/Views/BossViewModels/Edit1.cshtml
@model FirstProject.Models.BossViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>BossViewModel</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @*@Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @*@Html.LabelFor(model => model.KdTime, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.KdTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KdTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @*@Html.LabelFor(model => model.KdCount, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.KdCount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.KdCount, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.LastTime, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastTime, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastTime, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>