FirstProject/Controllers/ChangeUserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;
using FirstProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;

namespace FirstProject.Controllers
{
    public class ChangeUserController : Controller
    {
        // GET: ChangeUser
        [Authorize]
        public ActionResult Index()
        {

            var uc = new ApplicationDbContext();
            var userList = uc.Users.ToList();
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            
            Dictionary<string, string> users = new Dictionary<string, string>();
            foreach (var user in userList)
            {
                var email = user.Email;
                var nick = user.UserName;
                
                var us = userManager.FindByEmail(email);
                if (us != null)
                {
                    var roles = userManager.GetRoles(us.Id);
                    if (roles.Count<1) continue;
                    
                    users.Add(string.Format("{0}/{1}", email, nick), roles[0]);
                }
                
            }
            ViewBag.users = users;
            return View();
        }




        
        [HttpGet]
        public async Task<ActionResult> Edit(string email)
        {
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var rm = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
            email = email.Remove(email.IndexOf('/'));
            var rs = rm.Roles;
            List<string> roles = new List<string>();
            foreach (var r in rs)
            {
                roles.Add(r.Name);   
            }
            ApplicationUser user = await userManager.FindByEmailAsync(email);
            if (user != null)
            {
                ViewBag.roles = roles.ToList();
                ViewBag.user = user;
                ViewBag.userRole = await userManager.GetRolesAsync(user.Id);
                
                return View();
            }
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<ActionResult> Edit(string email,string nick,string role,string pass=null)
        {
            
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            ApplicationUser user = await userManager.FindByEmailAsync(email);
            if (user != null)
            {
                
                user.Email = email;
                user.UserName = nick;
                await userManager.RemoveFromRoleAsync(user.Id, userManager.GetRoles(user.Id)[0]);
                await userManager.AddToRoleAsync(user.Id, role);
                if (pass != null && pass!=string.Empty)
                {

                    var res = await userManager.UpdateAsync(user);
                    if (res.Succeeded)
                    {
                        await userManager.RemovePasswordAsync(user.Id);
                        await userManager.AddPasswordAsync(user.Id, pass);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("","Пользователь не обновлен");
                    }
                    //userManager.ResetPasswordAsync(user.Id, u.GetPassword() , pass);

                }
                else
                {
                    var result = await userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("","Пользователь не обновлен");

                    }
                }
            }
            else
            {
                        ModelState.AddModelError("","Пользователь не найден");

            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(RegisterViewModel model)
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.NickName, Email = model.Email };
                var result = await userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(user.Id, "Solder");
                    

                    // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error);
                }
            }

            // If we got this far, something failed, redisplay form
            return View(model);
            
        }
       
        public async Task<ActionResult> Delete(string email)
        {
            ApplicationUserManager userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            email = email.Remove(email.IndexOf('/'));
            ApplicationUser user = await userManager.FindByEmailAsync(email);
            if (user != null)
            {
                await userManager.DeleteAsync(user);
            }

            return RedirectToAction("Index");
        }
    }
}

FirstProject/Views/ChangeUser/Create.cshtml
@model FirstProject.Models.RegisterViewModel

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Регистрация нового пользователя</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NickName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NickName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NickName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

FirstProject/Views/ChangeUser/Edit.cshtml
@using System.Web.WebPages.Html
@using Microsoft.Ajax.Utilities
@using SelectListItem = System.Web.Mvc.SelectListItem

<link type="text/css" href="~/Content/Site.css" rel="stylesheet" />
@using (@Html.BeginForm("Edit", "ChangeUser",FormMethod.Post))
{
<div class="modal-content">
    <div class="modal-header">
       

        <h4>Информация о пользователе</h4>
    </div>
    <div class="modal-body">
        <p>
            @Html.Label("Email")
            <input id="email" type="text" name="email" value="@ViewBag.user.Email" readonly/>
        </p>
        <p>
            @Html.Label("Nickname")
            <input id="nick" type="text" name="nick" value="@ViewBag.user.UserName"/>
        </p>
        <p>
            @Html.Label("Текущее звание")
            <input id="role" type="text" name="role" value="@ViewBag.userRole[0]"/>
            <select id="selectedRoles" onchange="SetNewRole(this)">
                <option disabled>Выберите роль</option>
                <option>@ViewBag.roles[0]</option>
                <option>@ViewBag.roles[1]</option>
                <option>@ViewBag.roles[2]</option>
            </select>
            
        </p>
        <p>
            <script type="text/javascript">
                function showPas(box) {
                    var vis = (box.checked) ? "block" : "none";
                    document.getElementById('pwd').style.display = vis;
                }

                function SetNewRole(select) {
                    var i = document.getElementById('selectedRoles');
                    var roleName = i.options[i.selectedIndex].text;
                    document.getElementById('role').value = roleName;
                }
            </script>
            <b>Хотите изменить пароль?</b> <input type="checkbox" name =" showPWD" value="0" onclick="showPas(this)"/>
            <div id="pwd" style="display: block; display: none">
                @Html.Label("Password")
                <input type="text" name="pass"/>
            </div> 
        
           
        </p>
        <p>
           
            
                <input type="submit" class="button_1596547873487" value="Сохранить изменения"/>
                <a href="/ChangeUser/Index" class="button_1596547873487">
                    Оставить как есть
                </a>
           
            
        </p>
    </div>
</div>
}

FirstProject/Views/ChangeUser/GetAllUsers.cshtml
@Model MembershipUserCollection;
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetAllUsers</title>
</head>
<body>
<div>
    
</div>
</body>
</html>

FirstProject/Views/ChangeUser/Index.cshtml
@using FirstProject.Models;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link type="text/css" href="~/Content/Site.css" rel="stylesheet"/>
    <title>Index</title>
</head>
<body>
<div>

</div>
<div>

    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            Email/Никнейм
                        </th>
                        <th>
                            Роль/Звание
                        </th>
                        <th>
                            Действие
                        </th>
                    </tr>
                    @foreach (var user in ViewBag.users)
                    {
                        <tr>
                            <td>@user.Key</td>

                            <td>@user.Value</td>
                            <td>
                                <div class="link" font="latin">
                                    @Html.ActionLink("Edit", "Edit", new { email = user.Key })
                                    @Html.ActionLink("Delete", "Delete", new { email = user.Key }
                                        , new { onclick = "return confirm('Are you sure you wish to delete this article?');" })
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
        <div class="col-md-4">
            
                @using (@Html.BeginForm("Create", "ChangeUser", FormMethod.Get))
                {
                    <input type="submit" value="Создать нового пользователя" class="button_1596547873487"/>
                }
            
        </div>
    </div>
    
</div>
</body>
</html>